### ISSUE TITLE
T_INTLIFE: Relative time is not fixed to 8 octets

### ISSUE THREAD

**Issue by cgundogan** [icnrg/draft-gundogan-icnrg-ccnx-timetlv#3]
The current version of the draft (-00) states:
```
6.  IANA Considerations

   Please change the registry for the T_INTLIFE to permit a length of 1
   or 2 in addition to a length of 8, as follows:.


                        1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +---------------+---------------+---------------+---------------+
   |             T_INTLIFE         |               1               |
   +---------------+---------------+---------------+---------------+
   | INTERVAL_TIME |
   +---------------+

                        1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +---------------+---------------+---------------+---------------+
   |             T_INTLIFE         |               2               |
   +---------------+---------------+---------------+---------------+
   |           INTERVAL_TIME       |
   +-------------------------------+
```
But according to [RFC8609](https://tools.ietf.org/html/rfc8609#section-3.4.1),[RFC8569](https://tools.ietf.org/html/rfc8569#section-2.1), relative time is expressed with a variable-length TLV (not fixed to 8 octets). In fact, `Length` can be any number > 0. A fixed length of 8 octets is only true for absolute time, which is expressed in UTC (msec) since epoch.

However: 1 octet yields max 255 msec, 2 octets yield max ~65 seconds. The usefulness of `length=1` and `length=2` is therefore questionable.

Since this document is (because of the above) not only *adding* functionality, but also *replacing* existing behaviour, we may need further elaboration on *what* is *how* is replaced.

**Comment by daveoran** [comment]
We have material on upward/downward compatibility, and can spin in the results of the exchanges with Marc Mosko. I think we have this dealt with based on those, so I'm closing this issue.
